/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { appControllerGetHealth } from '../fn/app/app-controller-get-health';
import { AppControllerGetHealth$Params } from '../fn/app/app-controller-get-health';

@Injectable({ providedIn: 'root' })
export class AppService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `appControllerGetHealth()` */
  static readonly AppControllerGetHealthPath = '/api/health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appControllerGetHealth()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetHealth$Response(params?: AppControllerGetHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return appControllerGetHealth(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appControllerGetHealth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appControllerGetHealth(params?: AppControllerGetHealth$Params, context?: HttpContext): Observable<void> {
    return this.appControllerGetHealth$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
