/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ReadUserDto } from '../models/read-user-dto';
import { userControllerCreate } from '../fn/user/user-controller-create';
import { UserControllerCreate$Params } from '../fn/user/user-controller-create';
import { userControllerFindAll } from '../fn/user/user-controller-find-all';
import { UserControllerFindAll$Params } from '../fn/user/user-controller-find-all';
import { userControllerFindMe } from '../fn/user/user-controller-find-me';
import { UserControllerFindMe$Params } from '../fn/user/user-controller-find-me';
import { userControllerFindOne } from '../fn/user/user-controller-find-one';
import { UserControllerFindOne$Params } from '../fn/user/user-controller-find-one';
import { userControllerRemove } from '../fn/user/user-controller-remove';
import { UserControllerRemove$Params } from '../fn/user/user-controller-remove';
import { userControllerUpdate } from '../fn/user/user-controller-update';
import { UserControllerUpdate$Params } from '../fn/user/user-controller-update';

@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `userControllerFindAll()` */
  static readonly UserControllerFindAllPath = '/api/user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerFindAll$Response(params?: UserControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReadUserDto>>> {
    return userControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerFindAll(params?: UserControllerFindAll$Params, context?: HttpContext): Observable<Array<ReadUserDto>> {
    return this.userControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ReadUserDto>>): Array<ReadUserDto> => r.body)
    );
  }

  /** Path part for operation `userControllerCreate()` */
  static readonly UserControllerCreatePath = '/api/user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerCreate$Response(params: UserControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadUserDto>> {
    return userControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerCreate(params: UserControllerCreate$Params, context?: HttpContext): Observable<ReadUserDto> {
    return this.userControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReadUserDto>): ReadUserDto => r.body)
    );
  }

  /** Path part for operation `userControllerFindMe()` */
  static readonly UserControllerFindMePath = '/api/user/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerFindMe()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerFindMe$Response(params?: UserControllerFindMe$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadUserDto>> {
    return userControllerFindMe(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerFindMe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerFindMe(params?: UserControllerFindMe$Params, context?: HttpContext): Observable<ReadUserDto> {
    return this.userControllerFindMe$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReadUserDto>): ReadUserDto => r.body)
    );
  }

  /** Path part for operation `userControllerFindOne()` */
  static readonly UserControllerFindOnePath = '/api/user/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerFindOne()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerFindOne$Response(params: UserControllerFindOne$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadUserDto>> {
    return userControllerFindOne(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerFindOne$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerFindOne(params: UserControllerFindOne$Params, context?: HttpContext): Observable<ReadUserDto> {
    return this.userControllerFindOne$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReadUserDto>): ReadUserDto => r.body)
    );
  }

  /** Path part for operation `userControllerRemove()` */
  static readonly UserControllerRemovePath = '/api/user/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerRemove()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerRemove$Response(params: UserControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadUserDto>> {
    return userControllerRemove(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerRemove$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerRemove(params: UserControllerRemove$Params, context?: HttpContext): Observable<ReadUserDto> {
    return this.userControllerRemove$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReadUserDto>): ReadUserDto => r.body)
    );
  }

  /** Path part for operation `userControllerUpdate()` */
  static readonly UserControllerUpdatePath = '/api/user/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdate$Response(params: UserControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadUserDto>> {
    return userControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdate(params: UserControllerUpdate$Params, context?: HttpContext): Observable<ReadUserDto> {
    return this.userControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<ReadUserDto>): ReadUserDto => r.body)
    );
  }

}
