/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReadAnswerDto } from '../../models/read-answer-dto';

export interface AnswerControllerRemove$Params {
  id: string;
  patientId: string;
}

export function answerControllerRemove(http: HttpClient, rootUrl: string, params: AnswerControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadAnswerDto>> {
  const rb = new RequestBuilder(rootUrl, answerControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('patientId', params.patientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReadAnswerDto>;
    })
  );
}

answerControllerRemove.PATH = '/api/patient/{patientId}/answer/{id}';
