/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReadAnswerDto } from '../../models/read-answer-dto';

export interface AnswerControllerFindAll$Params {
  patientId: string;
}

export function answerControllerFindAll(http: HttpClient, rootUrl: string, params: AnswerControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReadAnswerDto>>> {
  const rb = new RequestBuilder(rootUrl, answerControllerFindAll.PATH, 'get');
  if (params) {
    rb.path('patientId', params.patientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReadAnswerDto>>;
    })
  );
}

answerControllerFindAll.PATH = '/api/patient/{patientId}/answer';
