/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateAnswerDto } from '../../models/create-answer-dto';
import { ReadAnswerDto } from '../../models/read-answer-dto';

export interface AnswerControllerCreate$Params {
  patientId: string;
      body: CreateAnswerDto
}

export function answerControllerCreate(http: HttpClient, rootUrl: string, params: AnswerControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadAnswerDto>> {
  const rb = new RequestBuilder(rootUrl, answerControllerCreate.PATH, 'post');
  if (params) {
    rb.path('patientId', params.patientId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReadAnswerDto>;
    })
  );
}

answerControllerCreate.PATH = '/api/patient/{patientId}/answer';
