FROM        nginx:1.21-alpine
ENV         TZ=Europe/Rome
RUN         ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
COPY        ./dist/fuse /usr/share/nginx/html
COPY        ./frontend.conf.template /etc/nginx/templates/frontend.conf.template
EXPOSE 8080
