version: '3'

services:
  frontend:
    #image: nginx:latest
    image: coop-fe-prod:1.0.0
    build: ./frontend
    restart: unless-stopped
    ports:
      - 8083:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx/

  backend:
    image: coop-be-prod:1.0.4
    container_name: ${BE_CONTAINER_NAME:-backend}
    build: ./backend
    restart: unless-stopped
    ports:
      - 8082:${BE_INTERNAL_PORT:-3000}
    environment:
     - NODE_ENV=production
