FROM        registry.access.redhat.com/ubi9/nodejs-20

ARG         NODE_ENV=production
ENV         NODE_ENV=${NODE_ENV}
ENV         TZ=Europe/Rome

COPY        package*.json ./ 
RUN         npm ci --omit=dev

COPY        ./dist /opt/app-root/src/dist

EXPOSE 3000
CMD ["node", "dist/main.js"]