apiVersion: v1
kind: Service
metadata:
  name: {{ include "coop-questionari.fullname" . }}-backend
  labels:
    {{- include "coop-questionari.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "coop-questionari.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
