/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateQuestionOptionDto } from '../models/create-question-option-dto';
export interface CreateSingleQuestionDto {
  controlType: 'textbox' | 'dropdown' | 'number' | 'divider';
  key: string;
  label?: string;
  options?: Array<CreateQuestionOptionDto>;
  order: number;
  type?: 'checkbox' | 'color' | 'date' | 'datetime-local' | 'email' | 'file' | 'hidden' | 'image' | 'month' | 'number' | 'password' | 'radio' | 'range' | 'reset' | 'search' | 'submit' | 'tel' | 'text' | 'time' | 'url' | 'week' | 'dropdown' | 'no-divider';
  valueType: 'string' | 'number';
}
