/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateQuestionOptionDto {
  key: string;
  value?: string;
  valueType: 'string' | 'number';
}
