/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IdNameGenderDto } from '../models/id-name-gender-dto';
import { ReadSingleAnswerDto } from '../models/read-single-answer-dto';
import { ReadSingleResponseDto } from '../models/read-single-response-dto';
import { ReadSingleTextDto } from '../models/read-single-text-dto';
export interface ReadAnswerDto {
  answers: Array<ReadSingleAnswerDto>;
  createdAt: string;
  id: string;
  notes?: string;
  patient: string;
  questionnaire: 'sf12' | 'ambiente' | 'sharefi75' | 'parametri' | 'neonati' | 'generic';
  results?: Array<ReadSingleResponseDto>;
  textResponses: Array<ReadSingleTextDto>;
  user?: IdNameGenderDto;
}
