/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReadSingleQuestionOptionNumberDto {
  key: string;
  value: number;
  valueType: 'number';
}
