/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReadUserDto } from '../models/read-user-dto';
export interface ReadCoopDto {
  email: string;
  id: string;
  name: string;
  phone?: string;
  users: Array<ReadUserDto>;
}
