/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SingleQuestionNumberDto } from '../models/single-question-number-dto';
import { SingleQuestionStringDto } from '../models/single-question-string-dto';
export interface ReadQuestionDto {
  createdAt?: string;
  description?: string;
  id: string;
  name: string;
  questionnaire: 'sf12' | 'ambiente' | 'sharefi75' | 'parametri' | 'neonati' | 'generic';
  results: Array<(SingleQuestionStringDto | SingleQuestionNumberDto)>;
  singleQuestion: Array<(SingleQuestionStringDto | SingleQuestionNumberDto)>;
}
