/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReadPatientDto {
  code: string;
  gender: 'm' | 'f';
  id: string;
  notes?: string;
  yearOfBirth: number;
}
