/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReadUserDto } from '../models/read-user-dto';
export interface SignInResponseDto {
  accessToken: string;
  expiresIn: number;
  tokenType: 'bearer';
  user: ReadUserDto;
}
