/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUserDto {
  coop?: string;
  email?: string;
  gender?: 'm' | 'f';
  name?: string;
  password?: string;
  role?: 'admin' | 'coop_admin' | 'user';
  yearOfBirth?: number;
}
