/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateSingleQuestionDto } from '../models/create-single-question-dto';
export interface UpdateQuestionDto {
  description?: string;
  name?: string;
  questionnaire?: 'sf12' | 'ambiente' | 'sharefi75' | 'parametri' | 'generic';
  singleQuestion?: Array<CreateSingleQuestionDto>;
}
