/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateSingleAnswerDto } from '../models/create-single-answer-dto';
import { CreateSingleResponseDto } from '../models/create-single-response-dto';
import { CreateSingleTextDto } from '../models/create-single-text-dto';
export interface UpdateAnswerDto {
  answers?: Array<CreateSingleAnswerDto>;
  notes?: string;
  questionnaire?: 'sf12' | 'ambiente' | 'sharefi75' | 'parametri' | 'neonati' | 'generic';
  results?: Array<CreateSingleResponseDto>;
  textResponses?: Array<CreateSingleTextDto>;
}
