/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePatientDto } from '../../models/create-patient-dto';
import { ReadPatientDto } from '../../models/read-patient-dto';

export interface PatientControllerCreate$Params {
      body: CreatePatientDto
}

export function patientControllerCreate(http: HttpClient, rootUrl: string, params: PatientControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadPatientDto>> {
  const rb = new RequestBuilder(rootUrl, patientControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReadPatientDto>;
    })
  );
}

patientControllerCreate.PATH = '/api/patient';
