/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReadPatientDto } from '../../models/read-patient-dto';

export interface PatientControllerFindAll$Params {
}

export function patientControllerFindAll(http: HttpClient, rootUrl: string, params?: PatientControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ReadPatientDto>>> {
  const rb = new RequestBuilder(rootUrl, patientControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ReadPatientDto>>;
    })
  );
}

patientControllerFindAll.PATH = '/api/patient';
