/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReadCoopDto } from '../../models/read-coop-dto';

export interface CoopControllerRemove$Params {
  id: string;
}

export function coopControllerRemove(http: HttpClient, rootUrl: string, params: CoopControllerRemove$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadCoopDto>> {
  const rb = new RequestBuilder(rootUrl, coopControllerRemove.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReadCoopDto>;
    })
  );
}

coopControllerRemove.PATH = '/api/coop/{id}';
