/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateCoopDto } from '../../models/create-coop-dto';
import { ReadCoopDto } from '../../models/read-coop-dto';

export interface CoopControllerCreate$Params {
      body: CreateCoopDto
}

export function coopControllerCreate(http: HttpClient, rootUrl: string, params: CoopControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<ReadCoopDto>> {
  const rb = new RequestBuilder(rootUrl, coopControllerCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ReadCoopDto>;
    })
  );
}

coopControllerCreate.PATH = '/api/coop';
