{{- if .Values.global.tlsEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coop-v2
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: coop-v2-tls
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend-v2
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend-v2
                port:
                  number: 8080
{{- end }}

