/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CreateAnswerDto } from './models/create-answer-dto';
export type { CreateCoopDto } from './models/create-coop-dto';
export type { CreatePatientDto } from './models/create-patient-dto';
export type { CreateQuestionDto } from './models/create-question-dto';
export type { CreateQuestionOptionDto } from './models/create-question-option-dto';
export type { CreateSingleAnswerDto } from './models/create-single-answer-dto';
export type { CreateSingleQuestionDto } from './models/create-single-question-dto';
export type { CreateSingleResponseDto } from './models/create-single-response-dto';
export type { CreateSingleTextDto } from './models/create-single-text-dto';
export type { CreateUserDto } from './models/create-user-dto';
export type { IdNameDto } from './models/id-name-dto';
export type { IdNameGenderDto } from './models/id-name-gender-dto';
export type { LoginDto } from './models/login-dto';
export type { ReadAnswerDto } from './models/read-answer-dto';
export type { ReadCoopDto } from './models/read-coop-dto';
export type { ReadPatientDto } from './models/read-patient-dto';
export type { ReadQuestionDto } from './models/read-question-dto';
export type { ReadSingleAnswerDto } from './models/read-single-answer-dto';
export type { ReadSingleQuestionOptionNumberDto } from './models/read-single-question-option-number-dto';
export type { ReadSingleQuestionOptionStringDto } from './models/read-single-question-option-string-dto';
export type { ReadSingleResponseDto } from './models/read-single-response-dto';
export type { ReadSingleTextDto } from './models/read-single-text-dto';
export type { ReadUserDto } from './models/read-user-dto';
export type { SignInResponseDto } from './models/sign-in-response-dto';
export type { SingleQuestionNumberDto } from './models/single-question-number-dto';
export type { SingleQuestionStringDto } from './models/single-question-string-dto';
export type { UpdateAnswerDto } from './models/update-answer-dto';
export type { UpdateCoopDto } from './models/update-coop-dto';
export type { UpdatePatientDto } from './models/update-patient-dto';
export type { UpdateQuestionDto } from './models/update-question-dto';
export type { UpdateUserDto } from './models/update-user-dto';
