export enum ControlSubTypeEnum {
  checkbox = 'checkbox',
  color = 'color',
  date = 'date',
  'datetime-local' = 'datetime-local',
  email = 'email',
  file = 'file',
  hidden = 'hidden',
  image = 'image',
  month = 'month',
  number = 'number',
  password = 'password',
  radio = 'radio',
  range = 'range',
  reset = 'reset',
  search = 'search',
  submit = 'submit',
  tel = 'tel',
  text = 'text',
  time = 'time',
  url = 'url',
  week = 'week',
  divider = 'divider',
  'no-divider' = 'no-divider',
  dropdown = 'dropdown',
  string = 'string',
  textbox = 'textbox',
}
