name: Deploy Helm Chart to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - 'helm/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Package Helm Chart
        run: |
          cd helm
          helm package .
          helm repo index . --url https://${{ github.repository_owner }}.github.io/coop-questionari

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./helm

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
